### PR TITLE
Create nl.json

### PR DESCRIPTION
**Pull request by ReneBreedveld**
First Dutch translation

### CODE REVIEW

**Review by otacke — CHANGES_REQUESTED** [review]
The field for the tab color seems to be missing, isn't it? Feel free to use https://translate-h5p.tk to avoid such issues (and have the benefit of other amenities).

**Comment by ReneBreedveld** [comment]
Yes I’ve noticed. I used the firtst version of your h5p-tabs. 

 

Should I fork a new file or do you prefer I’m using translate-h5p-tk?

 

Regards,

René

 

Van: Oliver Tacke ***@***.***> 
Verzonden: woensdag 13 maart 2024 14:24
Aan: otacke/h5p-tabs ***@***.***>
CC: René Breedveld ***@***.***>; Author ***@***.***>
Onderwerp: Re: [otacke/h5p-tabs] Create nl.json (PR #14)

 

@otacke requested changes on this pull request.

The field for the tab color seems to be missing, isn't it? Feel free to use https://translate-h5p.tk to avoid such issues (and have the benefit of other amenities).

**Comment by otacke** [comment]
@ReneBreedveld I don't have a preference, whatever works best for you. It's just that this type of issue would not have happened with translate-h5p.tk (others may :-)) and the platform has other benefits too, e.g. letting yourself be notified when there are new fields to be translated in a content type, easily checking how a word or phrase was translated in other content types for consistency, etc.

**Comment by otacke** [comment]
@ReneBreedveld Also, you don't need to create a new form when using github. Any consecutive commits to a branch that was used for a pull request will appear in that pull request automatically, too.

**Comment by ReneBreedveld** [comment]
Hi Oliver,

 

Thank you for making this clear. I’ll switch to translate-h5p.tk

 

Have a nice day,

René

 

Van: Oliver Tacke ***@***.***> 
Verzonden: woensdag 13 maart 2024 14:47
Aan: otacke/h5p-tabs ***@***.***>
CC: René Breedveld ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [otacke/h5p-tabs] Create nl.json (PR #14)

 

@ReneBreedveld <https://github.com/ReneBreedveld>  Also, you don't need to create a new form when using github. Any consecutive commits to a branch that was used for a pull request will appear in that pull request automatically, too.

**Pull request closed without merging**
